spring:
  application:
    name: CouponRedemptionService
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/coupon_redemption_service}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

geo-ip:
  base-url: ${GEO_IP_BASE_URL}
  connect-timeout: ${GEO_IP_CONNECT_TIMEOUT}
  read-timeout: ${GEO_IP_READ_TIMEOUT}
  excluded-addresses: ${GEO_IP_EXCLUDED_ADDRESSES}
